# Scan variables #
init:
  min_cores: 2
  hosts: []
  cidr: null
  ports: []
  nmap: "nmap -vv -sn -sV -sC -p <ports> <ip>"

# TCP based ports #
ftp:
  commands: []

ssh:
  commands: []

telnet:
  commands: []

smtp:
  commands: []

finger:
  commands: []

web:
  commands: []

pop3:
  commands: []

nntp:
  commands: []

imap:
  commands: []

snux:
  commands: []

smb:
  commands: []

rtsp:
  commands: []

cups:
  commands: []

kerberos_v5_admin_tcp:
  commands: []

kerberos_v4_passwd_tcp:
  commands: []

rsync:
  commands: []

iis:
  commands: []

mssql:
  commands: []

oracle_db:
  commands: []

oracle_xml_db:
  commands: []

sql:
  commands: []

oracle_web:
  commands: []

rdp:
  commands: []

adb:
  commands: []

vnc:
  commands: []

winrm:
  commands: []

adac:
  commands: []


# UDP based ports #
dhcp:
  commands: []

tftp:
  commands: []

kerberos_v5_passwd_udp:
  commands: []

kerberos_v5_ticket_udp:
  commands: []

mdns:
  commands: []


# TCP/UDP based ports #
wins:
  commands: []

dns:
  commands: []

kerberos_v5_ticket:
  commands: []

rpc:
  commands: []

ntp:
  commands: []

msrpc:
  commands: []

netbios_name:
  commands: []

netbios_sesh:
  commands: []

snmp:
  commands: []

ldap:
  commands: []

kerberos_v4_ticket:
  commands: []

kerberos_v4_admin:
  commands: []

windomain_indicator:
  commands: []

oracle_agent:
  commands: []

nfs:
  commands: []

globalcat_ldap:
  commands: []

upnotifyp:
  commands: []

rsip:
  commands: []

wsdapi:
  commands: []

dfsr:
  commands: []

wrms:
  commands: []