# Scan process variables #
init:
  max_tasks: 8
  nmap_init: []
  nmap_final: ""
  generate_markdown: False


# TCP based ports #
ftp:
  commands: []
  custom_commands: []

ssh:
  commands: []
  custom_commands: []

telnet:
  commands: []
  custom_commands: []

smtp:
  commands: []
  custom_commands: []

whois:
  commands: []
  custom_commands: []

finger:
  commands: []
  custom_commands: []

web:
  commands: []
  custom_commands: []

pop3:
  commands: []
  custom_commands: []

ident:
  commands: []
  custom_commands: []

nntp:
  commands: []
  custom_commands: []

imap:
  commands: []
  custom_commands: []

smux:
  commands: []
  custom_commands: []

checkpoint-firewall:
  commands: []
  custom_commands: []

smb:
  commands: []
  custom_commands: []

modbus:
  commands: []
  custom_commands: []

rlogin:
  commands: []
  custom_commands: []

rsh:
  commands: []
  custom_commands: []

apple_filing:
  commands: []
  custom_commands: []

rtsp:
  commands: []
  custom_commands: []

cups:
  commands: []
  custom_commands: []

rsync:
  commands: []
  custom_commands: []

java_rmi:
  commands: []
  custom_commands: []

mssql:
  commands: []
  custom_commands: []

oracle_db:
  commands: []
  custom_commands: []

oracle_xml_db:
  commands: []
  custom_commands: []

docker:
  commands: []
  custom_commands: []

squid:
  commands: []
  custom_commands: []

iscsi:
  commands: []
  custom_commands: []

sap_router:
  commands: []
  custom_commands: []

sql:
  commands: []
  custom_commands: []

rdp:
  commands: []
  custom_commands: []

distcc:
  commands: []
  custom_commands: []

subversion:
  commands: []
  custom_commands: []

epmd:
  commands: []
  custom_commands: []

cisco_smart_install:
  commands: []
  custom_commands: []

postgresql:
  commands: []
  custom_commands: []

redshift:
  commands: []
  custom_commands: []

vnc:
  commands: []
  custom_commands: []

winrm:
  commands: []
  custom_commands: []

x11:
  commands: []
  custom_commands: []

redis:
  commands: []
  custom_commands: []

java_debug_wire:
  commands: []
  custom_commands: []

apache_jserv:
  commands: []
  custom_commands: []

influxdb:
  commands: []
  custom_commands: []

bitcoin:
  commands: []
  custom_commands: []

apache_casandra:
  commands: []
  custom_commands: []

raw_printing:
  commands: []
  custom_commands: []

elastic_search:
  commands: []
  custom_commands: []

ndmp:
  commands: []
  custom_commands: []

memcache:
  commands: []
  custom_commands: []

gluster_fs:
  commands: []
  custom_commands: []

mongo_db:
  commands: []
  custom_commands: []

hadoop:
  commands: []
  custom_commands: []




# UDP based ports #
dhcp:
  commands: []
  custom_commands: []

tftp:
  commands: []
  custom_commands: []

ruserd:
  commmands: []
  custom_commands: []

ws_discovery:
  commands: []
  custom_commands: []

mdns:
  commands: []
  custom_commands: []

bacnet:
  commands: []
  custom_commands: []




# TCP/UDP based ports #
dns:
  commands: []
  custom_commands: []

kerberos:
  commands: []
  custom_commands: []

rpc:
  commands: []
  custom_commands: []

ntp:
  commands: []
  custom_commands: []

msrpc:
  commands: []
  custom_commands: []

nfs:
  commands: []
  custom_commands: []

rabbit_mq:
  commands: []
  custom_commands: []

couchdb:
  commands: []
  custom_commands: []

ethernet_ip:
  commands: []
  custom_commands: []