# Scan variables #
init:
  min_cores: 2
  hosts: []
  cidr: null
  ports: []
  nmap_init: []
  nmap_final: "nmap -vv -Pn -n -p- <host>"
  custom_program_path: "CustomPrograms"
  generate_markdown: False


# TCP based ports #
ftp:
  commands: []
  custom_commands: []

ssh:
  commands: []
  custom_commands: []

telnet:
  commands: []
  custom_commands: []

smtp:
  commands: []
  custom_commands: []

whois:
  commands: []
  custom_commands: []

finger:
  commands: []
  custom_commands: []

web:
  commands: []
  custom_commands: []

pop3:
  commands: []
  custom_commands: []

ident:
  commands: []
  custom_commands: []

nntp:
  commands: []
  custom_commands: []

imap:
  commands: []
  custom_commands: []

smux:
  commands: []
  custom_commands: []

checkpoint-firewall:
  commands: []
  custom_commannds: []

smb:
  commands: []
  custom_commands: []

modbus:
  commands: []
  custom_commands: []

rexec:
  commmands: []
  custom_commands: []

rlogin:
  commands: []
  custom_commands: []

rsh:
  commands: []
  custom_commands: []

lpd:
  commands: []
  custom_commands: []

apple_filing:
  commands: []
  custom_commands: []

rtsp:
  commands: []
  custom_commands: []

cups:
  commands: []
  custom_commands: []

kerberos_v5_admin_tcp:
  commands: []
  custom_commands: []

kerberos_v4_passwd_tcp:
  commands: []
  custom_commands: []

rsync:
  commands: []
  custom_commands: []

iis:
  commands: []
  custom_commands: []

java_rmi:
  commands: []
  custom_commands: []

mssql:
  commands: []
  custom_commands: []

oracle_db:
  commands: []
  custom_commands: []

pptp:
  commands: []
  custom_commands: []

mosquito:
  commands: []
  custom_commands: []

insight_manager:
  commands: []
  custom_commands: []

docker:
  commands: []
  custom_commands: []

squid:
  commands: []
  custom_commands: []

iscsi:
  commands: []
  custom_commands: []

sap_router:
  commands: []
  custom_commands: []

oracle_xml_db:
  commands: []
  custom_commands: []

sql:
  commands: []
  custom_commands: []

oracle_web:
  commands: []
  custom_commands: []

rdp:
  commands: []
  custom_commands: []

distcc:
  commands: []
  custom_commands: []

subversion:
  commands: []
  custom_commands: []

epmd:
  commands: []
  custom_commands: []

cisco_smart_install:
  commands: []
  custom_commands:

docker_registry:
  commands: []
  custom_commands: []

adb:
  commands: []
  custom_commands: []

postgresql:
  commands: []
  custom_commands: []

redshift:
  commands: []
  custom_commands: []

vnc:
  commands: []
  custom_commands: []

winrm:
  commands: []
  custom_commands: []

x11:
  commands: []
  custom_commands: []

redis:
  commands: []
  custom_commands: []

irc_tcp:
  commands: []
  custom_commands: []

apache_jserv:
  commands: []
  custom_commands: []

influxdb:
  commands: []
  custom_commands: []

splunkd:
  commands: []
  custom_commands: []

bitcoin:
  commands: []
  custom_commands: []

hypersql_db:
  commands: []
  custom_commands: []

apache_casandra:
  commands: []
  custom_commands: []

raw_printing:
  commands: []
  custom_commands: []

elastic_search:
  commands: []
  custom_commands: []

adac:
  commands: []
  custom_commands: []

ndmp:
  commands: []
  custom_commands: []

memcache:
  commands: []
  custom_commands: []

rabbit_mq_management:
  commands: []
  custom_commands: []

gluster_fs:
  commands: []
  custom_commands: []

mongo_db:
  commands: []
  custom_commands: []

tiller:
  commands: []
  custom_commands: []


# UDP based ports #
dhcp:
  commands: []
  custom_commands: []

tftp:
  commands: []
  custom_commands: []

kerberos_v5_passwd_udp:
  commands: []
  custom_commands: []

ipsec_ike_vpn:
  commands: []
  custom_commands: []

ruserd:
  commmands: []
  custom_commands: []

ws_discovery:
  commands: []
  custom_commands: []

kerberos_v5_ticket_udp:
  commands: []
  custom_commands: []

mdns:
  commands: []
  custom_commands: []

bacnet:
  commands: []
  custom_commands: []


# TCP/UDP based ports #
wins:
  commands: []
  custom_commands: []

dns:
  commands: []
  custom_commands: []

kerberos_v5_ticket:
  commands: []
  custom_commands: []

rpc:
  commands: []
  custom_commands: []

ntp:
  commands: []
  custom_commands: []

msrpc:
  commands: []
  custom_commands: []

netbios_name:
  commands: []
  custom_commands: []

netbios_sesh:
  commands: []
  custom_commands: []

snmp:
  commands: []
  custom_commands: []

irc:
  commands: []
  custom_commands: []

ldap:
  commands: []
  custom_commands: []

ipmi:
  commands: []
  custom_commands: []

kerberos_v4_ticket:
  commands: []
  custom_commands: []

kerberos_v4_admin:
  commands: []
  custom_commands: []

windomain_indicator:
  commands: []
  custom_commands: []

socks_proxy:
  commands: []
  custom_commands: []

oracle_agent:
  commands: []
  custom_commands: []

nfs:
  commands: []
  custom_commands: []

globalcat_ldap:
  commands: []
  custom_commands: []

upnotifyp:
  commands: []
  custom_commands: []

rsip:
  commands: []
  custom_commands: []

wsdapi:
  commands: []
  custom_commands: []

kibana:
  commands: []
  custom_commands: []

rabbit_mq:
  commands: []
  custom_commands: []

dfsr:
  commands: []
  custom_commands: []

couchdb:
  commands: []
  custom_commands: []

wrms:
  commands: []
  custom_commands: []

ethernet_ip:
  commands: []
  custom_commands: []