# Scan variables #
init:
  min_cores: 2
  hosts: []
  cidr: null
  ports: []
  nmap_init: [
    "nmap -vv -Pn -n -sS -T4 <host>",
    "nmap -vv -Pn -n -sU -T4 <host>",
    "nmap -vv -Pn -n -sV -T4 -sC <host>"
  ]
  nmap_final: "nmap -vv -Pn -n -p- <host>"
  custom_program_path: "CustomPrograms"
  generate_markdown: False


# TCP based ports #
ftp:
  commands: [
    "nc -vn <host> <port>",
    "telnet -n <host> <port>",
    "openssl s_client -connect <host>:<port> -starttls ftp",
    "wget --mirror ftp://anonymous:anonymous@<host>",
    "wget --mirror --no-passive ftp://anonymous:anonymous@<host>",
    "msfconsole -q -x 'use auxiliary/scanner/ftp/anonymous; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/ftp/ftp_version; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/ftp/bison_ftp_traversal; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/ftp/colorado_ftp_traversal; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/ftp/titanftp_xcrc_traversal; set RHOSTS <host>; set RPORT <port>; run; exit'"
  ]
  custom_commands: []

ssh:
  commands: [
    "nc -vn <host> <port>",
    "msfconsole -q -x 'use auxiliary/scanner/ssh/ssh_version; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use scanner/ssh/ssh_enumusers; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/ssh/juniper_backdoor; set RHOSTS <host>; set RPORT <port>; run; exit'"
  ]
  custom_commands: []

telnet:
  commands: [
    "nc -vn <host> <port>",
    "msfconsole -q -x 'use auxiliary/scanner/telnet/telnet_version; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/telnet/brocade_enable_login; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/telnet/telnet_encrypt_overflow; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/telnet/telnet_ruggedcom; set RHOSTS <host>; set RPORT <port>; run; exit'"
  ]
  custom_commands: []

smtp:
  commands: [
    "nc -vn <host> <port>",
    "nmap --script=smtp-commands,smtp-enum-users,smtp-vuln-cve2010-4344,smtp-vuln-cve2011-1720,smtp-vuln-cve2011-1764 -p <port> <host>",
    "openssl s_client -crlf -connect <host>:<port>",
    "openssl s_client -starttls smtp -crlf -connect <host>:<port>",
    "dig +short mx <host>",
    "msfconsole -q -x 'use auxiliary/scanner/smtp/smtp_version; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/smtp/smtp_ntlm_domain; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/smtp/smtp_relay; set RHOSTS <host>; set RPORT <port>; run; exit'"
  ]
  custom_commands: []

finger:
  commands: [
    "nc -vn <host> <port>",
    "finger @<host>",
    "finger admin@<host>"
  ]
  custom_commands: []

web:
  commands: [
    "nmap -vv --reason -Pn -sV -p <port> --script=`banner,(http* or ssl*) and not (brute or broadcast or dos or external or http-slowloris* or fuzzer)` <host>",
    "nikto -host <proto>://<host>",
    "gobuster dir -u <host>:<port> -t 50 --random-agent -w /usr/share/dirb/wordlists/common.txt --status-codes-blacklist \"301,404\"",
    "whatweb -a 4 <host>",
    "ffuf -w /usr/share/dirb/wordlists/common.txt:FUZZ -u <proto>://<host> -H \"Host: FUZZ.<host>\" -c -mc all"
  ]
  custom_commands: []

pop3:
  commands: [
    "nc -nv <host> <port>",
    "openssl s_client -connect <host>:<port> -crlf -quiet",
    "nmap --script \"pop3-capabilities or pop3-ntlm-info\" -sV -p <port> <ip>",
    "msfconsole -q -x 'use auxiliary/scanner/pop3/pop3_version; set RHOSTS <host>; set RPORT <port>; run; exit'"
  ]
  custom_commands: []

nntp:
  commands: []
  custom_commands: []

imap:
  commands: [
    "nc -nv <host> <port>",
    "openssl s_client -connect <host>:<port> -quiet",
    "msfconsole -q -x 'use auxiliary/scanner/imap/imap_version; set RHOSTS <host>; set RPORT <port>; run; exit'"
  ]
  custom_commands: []

snux:
  commands: []
  custom_commands: []

smb:
  commands: [
    "nbtscan <host>",
    "smbmap -H <host>",
    "smbmap -H <host> -u null -p null",
    "smbmap -H <host> -u guest",
    "smbclient -N -L //<host>",
    "smbclient -N //<host>/ --option=\"client min protocol\"=LANMAN1",
    "rpcclient <host>",
    "rpcclient -U \"\" <host>",
    "crackmapexec smb <host>",
    "crackmapexec smb <host> --pass-pol -u \"\" -p \"\"",
    "crackmapexec smb <host> --pass-pol -u \"guest\" -p \"\"",
    "msfconsole -q -x 'use auxiliary/scanner/smb/smb_version; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/smb/smb2; set RHOSTS <host>; set RPORT <port>; run; exit'",
  ]
  custom_commands: []

rtsp:
  commands: [
    "nmap -sV --script \"rtsp-*\" -p <port> <host>"
  ]
  custom_commands: []

cups:
  commands: []
  custom_commands: []

kerberos_v5_admin_tcp:
  commands: []
  custom_commands: []

kerberos_v4_passwd_tcp:
  commands: []
  custom_commands: []

rsync:
  commands: []
  custom_commands: []

iis:
  commands: []
  custom_commands: []

mssql:
  commands: [
    "nmap --script ms-sql-info,ms-sql-empty-password,ms-sql-xp-cmdshell,ms-sql-config,ms-sql-ntlm-info,ms-sql-tables,ms-sql-hasdbaccess,ms-sql-dac,ms-sql-dump-hashes --script-args mssql.instance-port=<port>,mssql.username=sa,mssql.password=,mssql.instance-name=MSSQLSERVER -sV -p <port> <host>",
    "msfconsole -q -x 'use auxiliary/scanner/mssql/mssql_ping; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/admin/mssql/mssql_enum; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use admin/mssql/mssql_enum_domain_accounts; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use admin/mssql/mssql_enum_sql_logins; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/admin/mssql/mssql_escalate_dbowner; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/admin/mssql/mssql_escalate_execute_as; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/admin/mssql/mssql_exec; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/admin/mssql/mssql_findandsampledata; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/mssql/mssql_hashdump; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/mssql/mssql_schemadump; set RHOSTS <host>; set RPORT <port>; run; exit'"
  ]
  custom_commands: []

oracle_db:
  commands: [
    "nmap --script \"oracle-tns-version\" -p <port> -T4 -sV <host>"
  ]
  custom_commands: []

oracle_xml_db:
  commands: []
  custom_commands: []

sql:
  commands: [
    "nmap --script=mysql-databases.nse,mysql-empty-password.nse,mysql-enum.nse,mysql-info.nse,mysql-variables.nse,mysql-vuln-cve2012-2122.nse <host> -p <port>",
    "msfconsole -q -x 'use auxiliary/scanner/mysql/mysql_version; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/mysql/mysql_authbypass_hashdump; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/admin/mysql/mysql_enum; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/mysql/mysql_hashdump; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/scanner/mysql/mysql_schemadump; set RHOSTS <host>; set RPORT <port>; run; exit'"
  ]
  custom_commands: []

oracle_web:
  commands: []
  custom_commands: []

rdp:
  commands: [
    "nmap --script \"rdp-enum-encryption or rdp-vuln-ms12-020 or rdp-ntlm-info\" -p <port> -T4 <host>"
  ]
  custom_commands: []

adb:
  commands: []
  custom_commands: []

vnc:
  commands: []
  custom_commands: []

winrm:
  commands: []
  custom_commands: []

adac:
  commands: []
  custom_commands: []


# UDP based ports #
dhcp:
  commands: []
  custom_commands: []

tftp:
  commands: [
    "nmap -n -Pn -sU -p <port> --script tftp-enum",
    "msfconsole -q -x 'use auxiliary/admin/tftp/tftp_transfer_until; set RHOSTS <host>; set RPORT <port>; run; exit'"
  ]
  custom_commands: []

kerberos_v5_passwd_udp:
  commands: []
  custom_commands: []

kerberos_v5_ticket_udp:
  commands: []
  custom_commands: []

mdns:
  commands: [
    "nmap -Pn -sUC -p5353 <host>"
  ]
  custom_commands: []


# TCP/UDP based ports #
wins:
  commands: []
  custom_commands: []

dns:
  commands: [
    "dnsrecon -r 127.0.1.0/24 -n <host>",
    "nslookup <host>",
    "dig -t _gc._<host> && dig -t _ldap._<host> && dig -t _kerberos._<host> && dig -t _kpasswd._<host>",
    "nmap --script dns-srv-enum --script-args \"dns-srv-enum.domain=<host>\"",
    "msfconsole -q -x 'use auxiliary/scanner/dns/dns_amp; set RHOSTS <host>; set RPORT <port>; run; exit'",
    "msfconsole -q -x 'use auxiliary/gather/enum_dns; set RHOSTS <host>; set RPORT <port>; run; exit'"
  ]
  custom_commands: []

kerberos_v5_ticket:
  commands: []
  custom_commands: []

rpc:
  commands: [
    "whois -h <host> -p 43 && echo <host> | nc -vn <host> 43",
    "nmap -sSUC -p <port> <host>"
  ]
  custom_commands: []

ntp:
  commands: [
    "nmap -sU -sV --script \"ntp* and (discovery or vuln) and not (dos or brute)\" -p <port> <host>"
  ]
  custom_commands: []

msrpc:
  commands: []
  custom_commands: []

netbios_name:
  commands: [
    "nmblookup -A <host>",
    "nbtscan <host>/30",
    "nmap -sU -sV -T4 --script nbstat.nse -p <port> -Pn -n <host>"
  ]
  custom_commands: []

netbios_sesh:
  commands: [
    "nmblookup -A <host>",
    "nbtscan <host>/30",
    "nmap -sU -sV -T4 --script nbstat.nse -p <port> -Pn -n <host>"
  ]
  custom_commands: []

snmp:
  commands: [
    "snmp-check <host>",
    "nmap --script \"snmp* and not snmp-brute\" <host>"
  ]
  custom_commands: []

ldap:
  commands: [
    "nmap -p <port> --script ldap-search -Pn <host>",
    "ldapsearch -H ldap://<host> -x",
    "ldapsearch -H ldap://<host> -x -s base namingcontexts"
  ]
  custom_commands: []

kerberos_v4_ticket:
  commands: []
  custom_commands: []

kerberos_v4_admin:
  commands: []
  custom_commands: []

windomain_indicator:
  commands: []
  custom_commands: []

oracle_agent:
  commands: []
  custom_commands: []

nfs:
  commands: [
    "nmap --script=nfs-ls.nse,nfs-showmount.nse,nfs-statfs.nse -p <port> <host>"
  ]
  custom_commands: []

globalcat_ldap:
  commands: []
  custom_commands: []

upnotifyp:
  commands: []
  custom_commands: []

rsip:
  commands: []
  custom_commands: []

wsdapi:
  commands: []
  custom_commands: []

dfsr:
  commands: []
  custom_commands: []

wrms:
  commands: []
  custom_commands: []