# Scan variables #
init:
  max_tasks: "This specifies the number of maximum asyncio scanning events that occur simultaneously"
  nmap_init: "This is the list of command syntax initial orchestration of nmap probing scans"
  nmap_final: "This is the command syntax for the final full port nmap scan"
  generate_markdown: "True/False boolean to set markdown output generation to on/off"


# The commands below all feature the capability of using parsing delimiters to dynamically format ip's, ports, etc.
# Available delimiters:
# <ip> - Parse in IPv4/IPv6 address
# <port> - Parse in port number
# <domain> - Parse in the target domain
# <proto> - Parse in the protocol name based on port number (supported: http, https)
# <path> - Parse in path to custom programs where the program name is not the first member, like python scripts. (use ONLY in custom_commands)
#          If not specified, it is assumed that the path to the custom program should be prepended to the beginning of the command.

# Note:  If the use of a " character is needed inside a command, it needs to be escaped like \" to properly parse


# It is only necessary to explain one of the services below since they all work the same

# TCP based ports #
ftp:
  commands: "This is where the commands that run programs tied to the system path go (example: nikto -host <ip>)"
  custom_commands: "This is where commands that run programs stored in custom program folder go (example: python <path>/test.py)"