# Scan variables #
init:
  min_cores: "This is used to specify the minimum number of processor cores to leave for the system"
  hosts: "This list is used to target specified hosts, if populated a ping scan will not be executed"
  cidr: "This is to specify the network CIDR for ping scan (ex: 10.0.0.0/24)"
  ports: "This list is to attack specific ports with toolchains, if populated nmap scans will not run"
  nmap_init: "This is the command syntax for the initial nmap ports of interest scan"
  nmap_final: "This is the command syntax for the final full port nmap scan"
  custom_program_path: "This is the name of the folder where custom programs to be stored for integration"


# It is only necessary to explain one of the services below since they all work the same

# TCP based ports #
ftp:
  commands: "This is where the commands that run programs tied to the system path go"
  custom_commands: "This is where commands that run programs stored in custom program folder go"

ssh:
  commands: []
  custom_commands: []

telnet:
  commands: []
  custom_commands: []

smtp:
  commands: []
  custom_commands: []

finger:
  commands: []
  custom_commands: []

web:
  commands: [
  "nmap -vv --reason -Pn -sV -p <port> --script=`banner,(http* or ssl*) and not (brute or broadcast or dos or external or http-slowloris* or fuzzer)` <ip>",
  "nikto -host <ip>",
  "gobuster dir -u <ip>:<port> -t 50 --random-agent -w /usr/share/dirb/wordlists/common.txt --status-codes-blacklist \"301,404\""
  ]
  custom_commands: []

pop3:
  commands: []
  custom_commands: []

nntp:
  commands: []
  custom_commands: []

imap:
  commands: []
  custom_commands: []

snux:
  commands: []
  custom_commands: []

smb:
  commands: []
  custom_commands: []

rtsp:
  commands: []
  custom_commands: []

cups:
  commands: []
  custom_commands: []

kerberos_v5_admin_tcp:
  commands: []
  custom_commands: []

kerberos_v4_passwd_tcp:
  commands: []
  custom_commands: []

rsync:
  commands: []
  custom_commands: []

iis:
  commands: []
  custom_commands: []

mssql:
  commands: []
  custom_commands: []

oracle_db:
  commands: []
  custom_commands: []

oracle_xml_db:
  commands: []
  custom_commands: []

sql:
  commands: []
  custom_commands: []

oracle_web:
  commands: []
  custom_commands: []

rdp:
  commands: []
  custom_commands: []

adb:
  commands: []
  custom_commands: []

vnc:
  commands: []
  custom_commands: []

winrm:
  commands: []
  custom_commands: []

adac:
  commands: []
  custom_commands: []


# UDP based ports #
dhcp:
  commands: []
  custom_commands: []

tftp:
  commands: []
  custom_commands: []

kerberos_v5_passwd_udp:
  commands: []
  custom_commands: []

kerberos_v5_ticket_udp:
  commands: []
  custom_commands: []

mdns:
  commands: []
  custom_commands: []


# TCP/UDP based ports #
wins:
  commands: []
  custom_commands: []

dns:
  commands: []
  custom_commands: []

kerberos_v5_ticket:
  commands: []
  custom_commands: []

rpc:
  commands: []
  custom_commands: []

ntp:
  commands: []
  custom_commands: []

msrpc:
  commands: []
  custom_commands: []

netbios_name:
  commands: []
  custom_commands: []

netbios_sesh:
  commands: []
  custom_commands: []

snmp:
  commands: []
  custom_commands: []

ldap:
  commands: []
  custom_commands: []

kerberos_v4_ticket:
  commands: []
  custom_commands: []

kerberos_v4_admin:
  commands: []
  custom_commands: []

windomain_indicator:
  commands: []
  custom_commands: []

oracle_agent:
  commands: []
  custom_commands: []

nfs:
  commands: []
  custom_commands: []

globalcat_ldap:
  commands: []
  custom_commands: []

upnotifyp:
  commands: []
  custom_commands: []

rsip:
  commands: []
  custom_commands: []

wsdapi:
  commands: []
  custom_commands: []

dfsr:
  commands: []
  custom_commands: []

wrms:
  commands: []
  custom_commands: []